name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate config.json
      run: bash -ec 'cat config.json | jq empty'
