[theme]
base="dark"
primaryColor="#f47b20"
secondaryBackgroundColor="#2e3192"
textColor="#fafafa"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false
headless=true

[browser]
gatherUsageStats=false
